### PR TITLE
Add credits easter egg

### PR DESCRIPTION
**Pull request by Govorunb**
https://github.com/Alexejhero/Vedal-Subnautica-Mod/assets/3830522/5678dbb9-6385-4327-bd88-eee8b06924a4

### CODE REVIEW

**Comment by Govorunb** [comment]
lgtm ;)

**Comment by Alexejhero** [comment]
no way you just lgtm'd your own pr and merged it

**Comment by Alexejhero** [comment]
aintnoway-aint

**Comment by Govorunb** [comment]
image

neurosama-neuro-sama

**Pull request merged**
